[31337]
endpoint_url = "http://anvil:8545"

[31337.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
order_engine = "0xa40E009b306B3b4f27374f6e833291DaAeC88cc6"
nft_c_0 = "0x6FE69253967982531bDe0C06476e7fe427f3F56c"
nft_c_1 = "0xC0Bd89573eDD265D3d9E0073f6D1e21e9Df5E1DA"

[31337.uint]
pipeline_start_ts = 1766023739
pipeline_end_ts = 1768442951
fork_start_block = 24036409
nft_c_count = 2
